import type { TaskSpecV2, TaskExecutionMode } from "../product/task-spec-v2.js";
import { implementationExecutorContract } from "../product/task-spec-contract.js";
import type { CommandDiagnostic } from "./validation-command-runner.js";
import type { ValidationAggregateStatus, ValidationPreflightPlan } from "../validation/capability-contract.js";
import type { SemanticReviewResult } from "./semantic-review.js";
import type { LogCompressionInvoker } from "./raw-log-compressor.js";

export type ExecutorStatus="ready"|"degraded"|"unavailable";
export type ImplementationExecutorCapability={id:string;status:ExecutorStatus;supports:TaskExecutionMode[];providerCalls:boolean;runtime:string[];providerRequirements:string[];networkRequirements:string[];maxLimits:Readonly<Record<keyof typeof implementationExecutorContract.maxLimits,number>>;limitations:string[];command:string|null;model:string|null};
export type ImplementationExecutorRequest={spec:TaskSpecV2;targetRepository:string;workingDirectory:string;projectProfile:Record<string,unknown>;acceptanceCriteria:string[];authorityEnvelope:TaskSpecV2["authority"];forbiddenZones:string[];runtimePolicy:TaskSpecV2["runtime"];validationProfile:TaskSpecV2["validation"];artifactRoot:string;attempt:number;generation:string;signal?:AbortSignal;onProgress?:(phase:string,detail:string)=>void|Promise<void>;executionAgreementId:string;logCompressionInvoker?:LogCompressionInvoker;checkpointRepair?:{patchPath:string;checkpointId:string;checkpointDigest:string;repairIntent:string|null}};
export type ImplementationExecutorResult={plan:string[];changedFiles:string[];patch:string;validationResults:CommandDiagnostic[];validationPlan:ValidationPreflightPlan;validationAggregate:ValidationAggregateStatus;unresolvedFindings:string[];status:"implemented_and_validated"|"no_change_required"|"blocked_with_owner_gate"|"failed_with_diagnostics";ownerGate:{required:boolean;reason:string|null};safetyAssertions:Record<string,boolean>;diagnostics:Record<string,unknown>;localBranch:string|null;localCommit:string|null;patchPackage:string|null;providerCalls:Array<Record<string,unknown>>;selectedExecutor:{id:string;model:string|null};review:{structural:{kind:"structural";status:ValidationAggregateStatus;evidence:string[]};semantic:SemanticReviewResult};checkpoints:Array<{id:string;path:string;patchPath:string;digest:string;iteration:number;validationPassed:boolean}>;budget:{exceeded:boolean;overrunPhase:"implementation"|"repair"|"review"|"logCompression"|null;requestedTokens:number;actualTokens:number;accounting:"provider"|"synthetic";costUsd:number|null}};
