import { mkdir, mkdtemp, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterEach, describe, expect, it } from "vitest";
import { CampaignCoordinator } from "../../src/control-plane/campaign-coordinator.js";
import type { CampaignPlan, CampaignSpec } from "../../src/control-plane/contracts.js";

const roots: string[] = [];
afterEach(async () => Promise.all(roots.splice(0).map((root) => rm(root, { recursive: true, force: true }))));

describe("campaign child runtime continuity", () => {
  it("holds a failed child with completed implementation checkpoint instead of creating a fresh implementation task", async () => {
    const root = roots[roots.push(await mkdtemp(join(tmpdir(), "runforge-campaign-continuity-"))) - 1]!; let creates = 0, repairs = 0, createdTask = false;
    const spec = campaignSpec(), task = { id: "implementation-task", status: "failed", error: "validation_failed", artifactRoot: join(root, "artifacts") } as any;
    const coordinator = new CampaignCoordinator({ root, planCampaign: async (record) => plan(record.id), createTask: async () => { creates += 1; createdTask = true; return task; }, getTask: async () => createdTask ? task : (() => { throw new Error("not found"); })(), getResult: async () => ({ status: "failed", workflow: { implementationCompleted: true }, implementation: { status: "implemented" }, artifact: { checkpoints: [{ id: "implementation-0", digest: "b".repeat(64) }] }, usage: { totalTokens: 100, costUsd: .01 } }), repairTaskFromCheckpoint: async () => { repairs += 1; return {}; }, integration: { ensureCampaignWorktree: async () => ({ worktreeRoot: join(root, "worktree"), branch: "runforge/test", headSha: "a".repeat(40) }) } as any });
    await coordinator.initialize(); const created = await coordinator.createCampaign(spec); const deadline = Date.now() + 2_000; let final = created;
    while (Date.now() < deadline && !["completed", "failed", "on_hold"].includes(final.status)) { await new Promise((resolve) => setTimeout(resolve, 10)); final = await coordinator.getCampaign(created.id); }
    expect(final).toMatchObject({ status: "on_hold", children: { implementation: { taskId: "implementation-task", status: "blocked", error: "campaign_checkpoint_repair_required", executionRetryAttempts: 0 } } });
    expect(creates).toBe(1); expect(repairs).toBe(0); await coordinator.drain();
  });

  it("replays one persisted checkpoint decision after a crash window without duplicate usage or reservation", async () => {
    const root = roots[roots.push(await mkdtemp(join(tmpdir(), "runforge-campaign-replay-"))) - 1]!, artifacts = join(root, "artifacts"); await mkdir(artifacts); await writeFile(join(artifacts, "implementation.patch"), "patch");
    const tasks = new Map<string, any>(), requests: any[] = []; let implementationCreates = 0, first = true, coordinatorA: CampaignCoordinator;
    const deps: any = { root, planCampaign: async (record: any) => plan(record.id), createTask: async ({ taskSpec }: any) => { const implementation = taskSpec.execution.mode === "implementation", task = { id: taskSpec.taskId, status: implementation ? "awaiting_owner_decision" : "completed", error: implementation ? "validation_failed" : null, artifactRoot: implementation ? artifacts : join(root, "validation") }; if (implementation) implementationCreates += 1; tasks.set(task.id, task); return task; }, getTask: async (id: string) => tasks.get(id) ?? (() => { throw new Error("not found"); })(), getResult: async (id: string) => tasks.get(id).status === "awaiting_owner_decision" ? checkpointResult(100) : tasks.get(id).id.includes("validation") ? { status: "completed", workflow: { status: "workflow_completed" }, validationAggregate: "passed", usage: { totalTokens: 25, costUsd: .001 } } : { status: "completed", workflow: { status: "workflow_completed" }, implementation: { status: "implemented_and_validated" }, validationAggregate: "passed", usage: { totalTokens: 50, costUsd: .005 } }, repairTaskFromCheckpoint: async (_id: string, request: any) => { requests.push(structuredClone(request)); const task = tasks.get(request.taskId); if (first) { first = false; task.status = "running"; coordinatorA.close(); } else task.status = "completed"; return { status: "repair_generation_started" }; }, integration: { ensureCampaignWorktree: async () => ({ worktreeRoot: join(root, "worktree"), branch: "runforge/test", headSha: "a".repeat(40) }), integrateChildPatch: async () => ({ headSha: "c".repeat(40), commit: "c".repeat(40) }) } };
    coordinatorA = new CampaignCoordinator(deps); await coordinatorA.initialize(); const created = await coordinatorA.createCampaign(campaignSpec());
    const crashDeadline = Date.now() + 2_000; while (Date.now() < crashDeadline && requests.length < 1) await new Promise((resolve) => setTimeout(resolve, 10)); await coordinatorA.drain();
    const persisted = await new CampaignCoordinator(deps).getCampaign(created.id); expect(persisted.children.implementation).toMatchObject({ status: "dispatching", accounted: false, executionRetryAttempts: 1, reservedTokens: 1, checkpointRepair: { state: "pending", decisionId: requests[0].decisionId, checkpointDigest: "b".repeat(64) } }); expect(persisted).toMatchObject({ usage: { tokens: 100, tasks: 1 }, reserved: { tokens: 1 } });
    const coordinatorB = new CampaignCoordinator(deps); await coordinatorB.initialize(); const deadline = Date.now() + 2_000; let final = await coordinatorB.getCampaign(created.id); while (Date.now() < deadline && !["completed", "failed", "on_hold"].includes(final.status)) { await new Promise((resolve) => setTimeout(resolve, 10)); final = await coordinatorB.getCampaign(created.id); }
    expect(final.status).toBe("completed"); expect(implementationCreates).toBe(1); expect(requests).toHaveLength(2); expect(requests[1]).toEqual(requests[0]); expect(final).toMatchObject({ usage: { tokens: 175, tasks: 3 }, reserved: { tokens: 0, costUsd: 0 }, children: { implementation: { status: "completed", checkpointRepair: { state: "started", decisionId: requests[0].decisionId } } } }); await coordinatorB.drain();
  });
});

function campaignSpec(): CampaignSpec { return { goal: "Implement once and validate", target: { repository: ".", workingDirectory: ".", expectedSha: "a".repeat(40) }, authority: { inspect: true, implementation: true, providerCalls: true, network: true, localBranch: true, localCommit: true, remotePush: false, draftPublication: false, merge: false, deploy: false }, providerRouting: { provider: "openrouter", model: "model/exact", fallbackPolicy: "none" }, limits: { maxTokens: 5_000, maxTasks: 2, maxConcurrency: 1 }, validationContract: { source: "explicit", requiredCommands: ["pnpm test"] } }; }
function checkpointResult(totalTokens: number): Record<string, unknown> { return { status: "awaiting_owner_decision", workflow: { implementationCompleted: true }, implementation: { status: "implemented" }, artifact: { checkpoints: [{ id: "implementation-0", digest: "b".repeat(64) }] }, usage: { totalTokens, costUsd: .01 } }; }
function plan(campaignId: string): CampaignPlan { const base = { target: { repository: ".", workingDirectory: ".", expectedSha: "a".repeat(40) }, providerRouting: { provider: "openrouter", models: { implementer: "model/exact", reviewer: "model/reviewer", logCompression: "model/log" }, maxCalls: 3, tokenBudget: { total: 2_000, perPhase: { planner: 0, implementer: 1_500, repair: 0, reviewer: 300, logCompression: 200 } }, retry: { maxAttempts: 1 }, fallbackPolicy: "none" }, git: { publication: "none" }, merge: { policy: "never" }, deploy: { policy: "never" } }; return { schemaVersion: 1, campaignId, estimatedTokens: 3_000, nodes: [{ id: "implementation", dependsOn: [], writeScopes: ["src"], estimatedTokens: 2_000, taskSpec: { ...structuredClone(base), taskId: `${campaignId}_implementation`, execution: { mode: "implementation", maxProviderTokens: 2_000 }, authority: { profile: "bounded-implementation", allowProviderCalls: true, allowNetwork: true }, discovery: { writeScopes: ["src"] }, validation: { mode: "explicit", commands: ["git diff --check"], requirements: [{ command: "git diff --check", acceptance: "advisory" }] } } }, { id: "validation", dependsOn: ["implementation"], writeScopes: [], estimatedTokens: 1_000, taskSpec: { ...structuredClone(base), taskId: `${campaignId}_validation`, execution: { mode: "validation", maxProviderTokens: 1_000 }, authority: { profile: "read-only", allowProviderCalls: false, allowNetwork: false }, discovery: { writeScopes: [] }, validation: { mode: "explicit", commands: ["pnpm test", "git diff --check __CAMPAIGN_BASE__...HEAD"], requirements: [{ command: "pnpm test", acceptance: "required" }, { command: "git diff --check __CAMPAIGN_BASE__...HEAD", acceptance: "required" }] } } }] }; }
